### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by johnfelipe** [IpshitaC/sociable#3]
Hi pls review

http://181.142.77.108:3016/

Not Authorized

```
felipe@felipeurrego:~/sociable$ node app.js
listening at: 3016
i18n module initialized
error: { code: 401, error: 'Not Authorized' } url: /api/profile
```

**Comment by IpshitaC** [comment]
Hi!
Are you having an issue with the API integration? Make sure you're using the API key correctly.

**Comment by IpshitaC** [comment]
Replace your credentials (username and password) in the app.js service wrapper to ensure authorization.
